name: Run Discord Bot Server

on:
  push:
    branches:
      - main
  # You can also trigger manually with workflow_dispatch

jobs:
  run-server:
    runs-on: ubuntu-latest

    env:
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}  # Pulls secret from GitHub Secrets

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run server
      run: |
        # The environment variable is available here
        node index.js
